export const awsConfig = {
  aws_project_region: '',
  aws_cognito_identity_pool_id: '',
  aws_cognito_region: '',
  aws_user_pools_id: '',
  aws_user_pools_web_client_id: '',
  oauth: {},
  aws_user_files_s3_bucket: '',
  aws_user_files_s3_bucket_region: '',
  aws_appsync_graphqlEndpoint: '',
  aws_appsync_region: '',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_appsync_apiKey: '',
  aws_mobile_analytics_app_id: '',
  aws_mobile_analytics_app_region: '',
};
